### ISSUE TITLE
direct download youtube videos

### ISSUE THREAD

**Issue by Arsh1219** [fent/node-ytdl-core#1035]
Is there any way to generate direct download links for youtube videos? the link I get with the API is to open the video. Then we see the player and hit the download button.

Is there any way to generate direct download link?

**Comment by danielsss** [comment]
+1 ?

**Comment by TimeForANinja** [comment]
not really - showing you the player is a browser behaviour
the browser decision is based on the content-type header
what you should be able to do is
a) somehow modify your browsers default behaviour
b) use a browser plugin
c) use a proxy that rewrites the header instead of requesting straight from youtube
