### ISSUE TITLE
Very slow downloads

### ISSUE THREAD

**Issue by mh4ck** [fent/node-ytdl-core#1057]
Hello, since a few days the lib is downloading youtube videos with around 50kbit/s.
Anyone else recognized this issue?

I've read that YouTube changed smth. but the n param should fix this. 
This is already commited in latest version (which i am using) but it still downloads very slow.

Is there a workaround or fix for this?

**Comment by augusto** [comment]
There is a fix on the latest version (4.10.1).

**Comment by augusto** [comment]
I kind of have the same issue. I have a little web app that gets the download links. If I download the file with the browser directly from googlevideo.com, the download is super fast. If I proxy the request through the web app (the web app fetches the file and streams it back), the transfer is slowish (~250kbps). I tested this with the app runs on my computer, so there's no really extra latency.

It could be a matter of setting the right headers so google thinks the request does come from a browser rather than a tool, as I get the same slowish transfer if I use the url with curl/wget.

**Comment by redbrain** [comment]
Previous issues with throttling were fixed as of v4.9.2. Can you replicate this behavior on the most recent version of ytdl-core?

**Comment by mh4ck** [comment]
@augusto Yes iam using the latest version ```"version": "4.10.1",``` but even with this fix it's slow

**Comment by TimeForANinja** [comment]
can you check if there's more bugs with the n-transform?

**Comment by Michal-Szczepaniak** [comment]
Yep, the previous fix was working until recently, reported by multiple people

**Comment by kiroslav** [comment]
This issue is still present

**Comment by gatecrasher777** [comment]
I notice this issue was raised 2 days after PR #1055.
The fix in #1055 was also applied in [ytcog](https://github.com/gatecrasher777/ytcog). 
Working with it every day since I have not picked up any consistent slowdowns.
If anyone can replicate the issue it would be helpful if the base.js address ```info.html5player``` can be recorded along with the slow video id.

**Comment by miniwa** [comment]
This is a problem for me as well and not just with downloads. Calls to `ytdl.getInfo` consistently take ~500ms to complete.

**Comment by MistakingManx** [comment]
I'm also having this issue, but now I'm getting 429 errors out of literally no where.

I've made no requests in the past 3 days and then suddenly my VPS got a 429 error on my first request. The IP is not shared.

**Comment by gatecrasher777** [comment]
Just to note there are no 429s using innertube requests, whether logged-in or not. 
And the info requests to https://www.youtube.com/youtubei/v1/player are instantaneous. 
This project could benefit a great deal from moving to the innertube api.

**Comment by TimeForANinja** [comment]
> Just to note there are no 429s using innertube requests, whether logged-in or not. And the info requests to https://www.youtube.com/youtubei/v1/player are instantaneous. This project could benefit a great deal from moving to the innertube api.

by now i'm personally down to switch but i'm not sure where to find the time to rewrite half the library 😅
