### ISSUE TITLE
[http] [player] [current time]

### ISSUE THREAD

**Issue by Orivoir** [fent/node-ytdl-core#1092]
Hi, thank for job.

- I've version `^4.11.0` of ytdl-core.
- I've not find a duplicate issue.
- My question is about using the library for a specific use case, but i've not find answers at [examples folder](https://github.com/fent/node-ytdl-core/tree/master/example).

I use `ytdl-core`  with [express](https://www.npmjs.com/package/express) i've a HTTP route send stream  that been create with `ytdl-core`, i use the below code snippet for emit stream:

```ts
    const createStream = (videoFormat?: videoFormat) => {
      response.header("Content-Disposition", "inline; filename=stream-yt.mp4");
      response.type('video/mp4');

      console.log(startAt);

      const stream = ytdl(`http://www.youtube.com/watch?v=${key}`, {
        format: videoFormat,
        begin: (typeof startAt === 'string' ? startAt: "0m0s")
      })

      stream.pipe(response, {
        end: true
      })
    }
```

It work but, at my browser with default controls media i cant set the *current time* of video.
I understand origin of this problem, but how i can implement a player javascript it work ?

This project has a folder [test/files/html5player](https://github.com/fent/node-ytdl-core/tree/master/test/files/html5player) with a list of browser javascript files, but i not find documentation of this files.

I find a reference into [example/discord.js](https://github.com/fent/node-ytdl-core/blob/master/example/discord.js#L26) file

https://github.com/fent/node-ytdl-core/blob/11103be3ab373551bddd0938bc0bbaea033acb8e/example/discord.js#L26

But usage is specific to discord.js.

**Comment by absidue** [comment]
My guess is that because you are streaming the file directly to the browser your browser has no way of knowing when the video actually starts so it thinks that it just starts from when the first amount data gets there. Also as you are streaming the data directly you have no idea how long it is so the browser is probably treating it as a live stream.

I don't know the exact way to fix it but you will likely need to implement custom video player controls so you can display the information on your website the way you want it to be.

Those test files are javascript from YouTube's website, they are there purely so that the test cases can check that ytdl-core extracts the information correctly. You won't find any documentation on them unless you start working for Google and can see the internal documentation for the YouTube's code.

Discord doesn't need to know when the audio starts so that doesn't help you either.

**Comment by Orivoir** [comment]
Thanks for feedback, ok i understand, i go attempt implemented a Javascript Player.
