### ISSUE TITLE
Should we find better way to make decipherScript?

### ISSUE THREAD

**Issue by phat-px95** [fent/node-ytdl-core#1107]
As far as I know, the version around 4.9.0 uses a different way of deciphering compared with 4.10.1 up to 4.11.0.

**For 4.10.1**: The current version I'm trying to use is 4.10.1, which latter will use **eval** and **createElement** in **runInContext** function (inside vm-browserify/index.js). It is not good for **Manifest V3** of Chrome Extensions.

**For 4.9.0**: It will fail to decipher some minor cases such as:
https://www.youtube.com/watch?v=G7J_Lpkqwmo
https://www.youtube.com/watch?v=4pCyRD4y6w0&t=59ss
It seems fine at first, but only one quality can be combined and downloaded, others are total failures.

Did anyone get the same problem?

An idea of any kind could be good. Thank you all!

**Comment by bangnopal** [comment]
yes, i have same problem with this

**Comment by JackReevies** [comment]
Does this have anything to do with deciphering failing completely on 4.11? I'm getting an error with sig.js line 116 with an unexpected token. Way above me to try debugging beyond this, that base.js file is insane

**Comment by depresif** [comment]
Got the 'unexpected token' also, opened an issue at #1108 @JackReevies

**Comment by gatecrasher777** [comment]
To find a better way:  I think the will is there, but perhaps not yet the time:

#1074 
#1057 

Todo: 
1) Move the getinfo process to YouTube's innertube API. 
2) Code simulations of the deciphering functions rather than running them directly.

**Comment by phat-px95** [comment]
Thank you all,
I found out that **4.9.1** is the best fit for me. Moving forward to **Manifest V3** on chrome, I think we should not use **4.10.x** or **4.11.x**, cause the use of **eval()** and **createElement** (which cannot use on service worker), or we can change the way of using vm-browserify.
I will keep this one open for some future improvements.

**Comment by phat-px95** [comment]
> 1. YouTube's innertube API

Thank you, changing to the new API could be a good idea. Getinfo died frequently.
For deciphering from base.js, that can be done by using regex and eval(), I suppose.

**Comment by LuanRT** [comment]
> 2. Code simulations of the deciphering functions rather than running them directly.

Unfortunately code simulations can be rather difficult to maintain as well — just so you can have an idea, the decipher I wrote for my repo also broke due to these changes YouTube made. And now that they're using [comma operators](https://stackoverflow.com/questions/40967162/what-is-the-meaning-of-this-code-0-function-in-javascript), dates, throwing & catching errors, it's become impossible to emulate it accurately. There's a solution though, ytdl could just migrate to InnerTube and use `ANDROID` as client (which doesn't require deciphering anything) or use a JavaScript interpreter.

Since there isn't any lightweight js interpreter written in pure js/ts that can handle YouTube's funny code I decided to write one myself. It's already able to run nsig's code but it's still very experimental, if anybody wants to help it can be found [here](https://github.com/LuanRT/Jinter).
