### ISSUE TITLE
Drop support for outdated node versions

### ISSUE THREAD

**Issue by TinyMan** [fent/node-ytdl-core#165]
According to https://github.com/nodejs/LTS#lts-schedule1, v0.10 v0.12 are in End-of-Life and 4.x is in maintenance. 

With node 8.x around the corner it may be the right time to drop support for older unstable versions.

**Comment by fent** [comment]
A while ago I thought which versions I should keep supporting. I came across [this source](https://semaphoreci.com/blog/2016/10/12/nodejs-versions-used-in-commercial-projects-2016-edition.html) that lists v0.12 as still being used substantially in 2016. Also, I didn't find it too limiting to not use some of the new things from v4. This is a decision made across all of the open source projects I maintain.

But, I can see how it could be annoying to want to contribute to a project, and not being able to use some es6 stuff.

**Comment by TinyMan** [comment]
Ha I was not expecting this answer.

I was amazed to see how v0.12 is still used in 2016. I cannot understand why people do that ... It's like those folks still using windows xp and doing no updates that Microsoft has to save because of some monthly cyber attack even if xp is no longer maintained. I understand it's a question of money for them (upgrading can be difficult and time taker) but still, windows xp ...

It's not only about those stuff of es6, but also about the good habits. Also, I think that if we keep older versions alive, they will never be dropped. Few years later we end up using thousands of different versions all across the web and it breaks things. And from what I know there is no problem running v0.12 code into newer releases. Over here I user v6.x and never had a problem running `ytdl` for example. What I'm saying is that people can still use their older dependencies with newer Node version.

If someone needs `ytdl` there are 2 cases:
* either they use stable Node version and it runs, and it would still run with `ytdl` supporting only stable / maintenance versions
* or they use old Node version. They have the choice to update their Node version or to shrinkwrap their dependency and not get new features/fix from `ytdl` as they do for Node. I cannot see where someone would actively develop anything today with only support for End-of-Life Node versions. Maintenance is another thing and they should not be expecting new features from dependencies.

That being said, I know that doing updates can sometimes break things up.

Anyway, I can understand your choice even if I wouldn't have done the same. It's up to you. You can close this if you chose to wait.

**Comment by fent** [comment]
> It's not only about those stuff of es6, but also about the good habits. Also, I think that if we keep older versions alive, they will never be dropped. Few years later we end up using thousands of different versions all across the web and it breaks things. And from what I know there is no problem running v0.12 code into newer releases.

The LTS schedule you linked above I think is a good way to go about it. People who are still using older versions get a warning about it, they know they have to update within a couple of years.

But I also try to follow what the whole community is doing... looking up some popular non-cli modules on npmjs.org, most of them still support v0.12, some even going all the way back to supporting v0.8 and v0.10.

https://github.com/request/request/blob/master/.travis.yml (v4 - latest)
https://github.com/caolan/async/blob/master/.travis.yml (v0.10 - v7)
https://github.com/chalk/chalk/blob/master/.travis.yml (v4, v6)
https://github.com/petkaantonov/bluebird/blob/master/.travis.yml (v0.10 - v6)
https://github.com/jashkenas/underscore/blob/master/.travis.yml (v0.8 - v0.12)
https://github.com/tj/commander.js/blob/master/.travis.yml (v0.6 - latest)
https://github.com/visionmedia/debug/blob/master/.travis.yml (v4 - v6)
https://github.com/expressjs/express/blob/master/.travis.yml (v0.10 - latest)

So there's a perspective from two sides, those who are using an outdated version and think "All of these modules support this version, why doesn't yours?" and those who are using a newer node version, want to contribute and think "Why are you still supporting an outdated version? It's annoying that I can't use feature x"

And due to the above LTS schedule providing enough warning, I'm agreeing more with the latter perspective. I can keep this issue opened until v0.12 support is removed, but I can't say I'll work on it soon.

**Comment by iCrawl** [comment]
I support removing older versions.

Yes you linked several cases where those node versions are still supported and I can see why. If you have a very big project that you built on v0.10 you surely don't wanna go through the pain of updating it each time a new node version comes out, but here is the problem: Node has a LTS schedule, so those developers are aware of when those version become outdated and receive no support anymore. At this point not even legacy software should run on such old versions imo.

I fully support staying on track with LTS though. Whether you choose to still support maintenance too (v4 in that case) is up to you. I don't think you have to go as far and "only" support LTS.

**Comment by TinyMan** [comment]
I'm not sure what needs to be done, in order to drop support for these. Change the travis config and start writing new update with no consideration for older release I would say .. right ? Or do we need as well to rewrite some parts ?

**Comment by fent** [comment]
I'd prefer to  rewrite the entire the whole library with node 4 support in mind. Otherwise, when new updates come in, we might have parts of files coded with es6 and others in the old way.

**Comment by TimeForANinja** [comment]
best reason to switch to at least v0.4 => https://github.com/mdevils/node-html-entities/blob/master/package.json#L33
