### ISSUE TITLE
Videos are being downloaded on server side, I want to download them on browser (client side).

### ISSUE THREAD

**Issue by saiumesh535** [fent/node-ytdl-core#181]
Videos are being downloaded on server side, I want to download them on browser (client side). like when someone requests from my website it should download on their browser as normally download would do.

**Comment by TinyMan** [comment]
If your purpose is to play the video, you should use youtube official player there.

If you want to download it you have either to download on the server side and then serve the file to the client, or you have to pack `ytdl` into a browser version. I think it shouldn't be a problem.

**Comment by fent** [comment]
You might not be able to use `ytdl` client side due to CRSF policies. Unless you put it inside of an extension or userscript.

You can also try getting the download link server side, give that to the client, have them download it. I'm not 100% positive that it will work though -- the download link might be tied to the IP.
