### ISSUE TITLE
ytdl.validateLink returns true when actually false

### ISSUE THREAD

**Issue by maxijonson** [fent/node-ytdl-core#230]
I'm using ytdl for a discord bot. I use ytdl.validateLink to make sure the user entered a valid link or ID, if he didn't, then the bot checks if its a name of a saved link, else, he uses simple-youtube-api to get the first link he gets from a video search by name. 

So I was testing the "get video by name" feature, tried "play call of duty", worked, tried "play adele", worked. Then, I tried "play battlefield" which crashed the bot. I searched everywhere, couldn't find the problem. Until I tried checking if ytdl.validateLink returned true (which  I was sure wouldn't) and it did return true, but "battlefield" is not a valid link nor ID... anyways, until this problem get's fixed, I found an alternative using ytdl.getInfo: (sorry, got no idea how to make code on github xd) 

var isYtdl = true;
// The following will throw an exception if it's not valid
let checkYtdl = await ytdl.getInfo(link).catch( (err) => {
isYtdl = false;
});

then, instead of using ytdl.validateLink(link) in if statement, I use isYtdl. This ain't so pretty, but it does the job for now, although it slows down my code because of the await it has to do now everytime.

Of course, I invite anyone to reproduce to proove it, maybe the issue isn't in ytdl and only on my side, but so far it has proven me right.

**Comment by Ovyerus** [comment]
![screenshot](https://owo.whats-th.is/dca9c0.png) definitely a thing with ytdl.
I looked through the source for what validates a link, https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L223-L244, and it seems to only check if the argument given is 11 characters long, and contains any of the characters that are valid in a YouTube video URL.

I'd suggest having some regex that checks the user input instead of using `ytdl.validateLink`.
I personally use `(?:https?:\/\/)?(?:(?:www\.|m.)?youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9-_]{11})` and I haven't had any issues with it so far

**Comment by fent** [comment]
`validateLink` returns true for that because video IDs are made up of 11 [alphanumeric character](https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L223), which "battlefield" is.

I could add another function that's more specific, `validateID`. And export the [`getVideoID`](https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L224) function to keep supporting the old behavior.

if your bot is crashing, that is another issue. You should be checking for and catching any errors from `getInfo()`, regardless if it's called with an actual valid link. Because other things could go wrong, the video could be unavailable, or made private, or blocked in your country.

**Comment by maxijonson** [comment]
Yes, the bot crashing is just me not handling the error (now it does), I was just curious to know why ytdl failed on validateLink and knowing that definitely gives me some clues on what I can do thanks!
