### ISSUE TITLE
Support DASH (audio) live streams

### ISSUE THREAD

**Issue by Dev-Yukine** [fent/node-ytdl-core#231]
when i try to download a livestream what is currently live i get the following error 
"TypeError: Request path contains unescaped characters"

 a full trace stack can be viewed [here](https://hastebin.com/ekuxujutit.js) 
an example to reproduce is [this](https://www.youtube.com/watch?v=saekEgHaIo0) live stream

NOTE from dev: You may find that some audio livestreams can be played for only a few seconds before they stop. That's an effect of this same issue.

**Comment by fent** [comment]
I'm not able to replicate. Could you post an example of how your bot uses ytdl?

**Comment by Dev-Yukine** [comment]
oh sure since i use it with Discord.js it look like this 
```js
const yt = require('ytdl-core');
voiceConnection.playStream(yt(link, { filter: 'audioonly' }));
```
where link is defined as the url of the livestream

**Comment by appellation** [comment]
I've found that this issue only appears when using `filter: 'audioonly'` as an option.

**Comment by fent** [comment]
Yep, I'm able to replicate with the filter.

**Comment by Gymnophoria** [comment]
If it's any help, I've found that the [segmentURL in m3u8stream's index file](https://github.com/fent/node-m3u8stream/blob/master/lib/index.js#L28) is garbled text when using `filter: 'audioonly`, whereas it is a proper URL without it.

**Comment by thomasxd24** [comment]
i found a fix for this, do 
`filter : 'audioonly' , quality: 94`
94 is the itag responsible for livestream.

**Comment by Dev-Yukine** [comment]
That fix doesn't seem to work for me.

**Comment by aletorrado** [comment]
+1

**Comment by MichaelPriebe** [comment]
+1 Getting this problem.

**Comment by Dev-Yukine** [comment]
i actually found a nice workaround on here instead using `yt(link, { filter: 'audioonly' })` use `yt(link, { audioonly: true })` and it works as expected, but #263 is happening then

**Comment by TimeForANinja** [comment]
@Dev-Yukine  doing `yt(link, { audioonly: true })` is basicly the same as `yt(link)` and will therefor also download the video part...

**Comment by Sikksens** [comment]
The workaround was working fine but getting this error on live streams with or without the filter now.

**Comment by MarcysVonEylau** [comment]
> filter : 'audioonly' , quality: 94

 Error: No such format found: 94

Why is that?

**Comment by BrunoMoreira991** [comment]
Is there actually any Livestream on Youtube with more **DASH (audio only)** formats available besides `139` and `140` **itags**? Because those are the only formats that I seem to find on every livestream I test, besides the **video+audio** formats (`91`, `92`, `93`, `94`, `95` **itags**) and other **video only** formats.

I assume that when you guys use `{ filter: 'audioonly' }` it will either use the `139` or `140` **itag** format, one of them (`140` **itag**) is only going to play for a few seconds - as it is **not live** - and the other one (`139` **itag**) currently seems to throw `TypeError: Request path contains unescaped characters`.

The only way to properly get the stream from a Youtube livestream right now is to simply not use the `audioonly` filter, forcing you to also download the video.

Btw, even if this gets fixed the `139` **itag** has, supposedly, only 48kbps audio bitrate - it's not exactly the greatest audio quality lol - so I hope there's some "privileged" streams out there with more DASH (audio only) formats that I'm not seeing because that's a *miserable* bitrate tbh.

**Comment by BrunoMoreira991** [comment]
Of course. 👍 I noticed that since the the fix the `140` itag **seems** to now stream the live audio instead of just a few seconds, and, compared to the `139` itag, it has a decent bitrate so it's great. 😃
