### ISSUE TITLE
The progress event is not firing when infooptions are present

### ISSUE THREAD

**Issue by Blackfaded** [fent/node-ytdl-core#373]
The progress event is not firing when infooptions are present.
On the first example the console.log prints nothing.
On the second example it prints as expected.

```js
import ytdl from 'ytdl-core';

 ytdl.
      downloadFromInfo(info, { quality: 'highestaudio', filter: 'audioonly' })    
     .on('progress', (length, downloaded, totallength) => {
        console.log({ length, downloaded, totallength }); // not logging
      })
```

```js
import ytdl from 'ytdl-core';

 ytdl.
      downloadFromInfo(info)    
     .on('progress', (length, downloaded, totallength) => {
        console.log({ length, downloaded, totallength }); // is logging
      })
```

But in both cases the download is finishing.
Is this the wanted behavior?

**Comment by Blackfaded** [comment]
I noticed that it is not happening on every video, but on some it is.
This is an [example of a video](https://www.youtube.com/watch?v=CmFxZd6bJkM) where i do not get the progress when filtering audio.

**Comment by fent** [comment]
Ok, now I'm able to reproduce this. Will fix in a bit

**Comment by fent** [comment]
Fix wasn't as simple as I thought. For some formats, dash and hls playlist formats, download progress is harder to track since videos are made up of several dozen segments. Calculating the total size of the video would mean going through every segment, which means we'd only have the total size at the end of the download.

Right now, `progress` will emit with chunk length and total downloaded. But not with the video's total size for these formats. I've added a note to the readme about this.

Beyond this, the best I can do is calculate segment progress. But this is a good solution for now.
