### ISSUE TITLE
Live streaming can't get urls.

### ISSUE THREAD

**Issue by a26364177** [fent/node-ytdl-core#398]
` 
ytdl.getInfo('u5X_hiHtKkM', (err, info) => { })
`

info.formats without any playable url.

**Comment by omarroth** [comment]
I've encountered this as well. Likely related to #399. Hopefully this is useful for @fent. The `hlsvp` and `dashmpd` urls have moved into the `player_response` as `hlsManifestUrl` and `dashManifestUrl`, respectively.

See rg3/youtube-dl#18799, which was fixed with [c3e5438](https://github.com/rg3/youtube-dl/commit/c3e543893bfba7faa7c13e53fbe6b60f936b81f1).
