### ISSUE TITLE
getURLVideoID error behaviour

### ISSUE THREAD

**Issue by nfearnley** [fent/node-ytdl-core#485]
Why does getURLVideoID() _return_ an error instead of _throwing_ an error? This is completely unintuitive, and is not documented.

**Comment by fent** [comment]
i think it used to throw before, and had people before ask why it throws, since throwing would break their node app if they hadn't wrapped it in a `try/catch` block.

ideally it would return `null` if it can't find the video id. but the error it returns are specific on why it wasn't able to find the video id: https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L272-L290

maybe it could work like

```js
[id, err] = getUrlVideoID(url);
```

which is a pattern common in golang

**Comment by nfearnley** [comment]
Generally, the convention I'd expect would be this:

Synchronous calls:
Return value or throw error
Return value or return null
Return value or return undefined

Callbacks:
Call callback with (err, value)

Promises:
Resolve with value or reject with err

Right now, by returning an error, I need to add the following to my calls
to prevent it from crashing:
var value = ytdl.getURLVideoID(input);
if (value instanceof Error) {
    // handle error
}

This isn't much different from a try catch, other than it's against
convention.

**Comment by TimeForANinja** [comment]
<3 git blame
https://github.com/fent/node-ytdl-core/issues/121

**Comment by fent** [comment]
@nfearnley there's a PR for a solution to this now https://github.com/fent/node-ytdl-core/pull/520

implementation looks good to me, what do you think?
