### ISSUE TITLE
stream not emitting 'format' event

### ISSUE THREAD

**Issue by andrewrk** [fent/node-ytdl-core#57]
The README says that request stream will emit a 'format' event: https://github.com/fent/node-ytdl-core#event-format

Looking at the code, I don't think this is happening anymore. Instead the stream is emitting an 'info' event. Is the code wrong, or is the readme wrong?

Another issue is that format used to have a `size` field (in bytes), and this field is now missing. Is there a way to get the size in bytes before downloading? Otherwise there's no way to have a progress bar.

**Comment by fent** [comment]
The readme is wrong, the format is available in the 'info' event. https://github.com/fent/node-ytdl-core#event-info

And since the following-redirects-change, the size can be obtained by listening for the 'response' event, which the cli module does https://github.com/fent/node-ytdl/blob/master/bin/ytdl.js#L242

Also should be added to the readme.

**Comment by andrewrk** [comment]
Thanks, confirmed everything is fixed now.

**Comment by usamamashkoor** [comment]
@andrewrk can you please let us know how did you get the file size before downloading it.
