### ISSUE TITLE
discordjs v12 : Could not extract html5player key: https://www.youtube.com/s/player/4fbb4d5b/player_ias.vflset/en_US/base.js

### ISSUE THREAD

**Issue by Spokloo** [fent/node-ytdl-core#602]
So i get this error message when i start playing music with my discord bot. I'm in v12 of discordjs and I don't know why i'm getting this error and I also don't know how to fix it. Can someone help me ? Thanks
PS : (On the closed issues that are similar, i can't manage to find any answer to my question so I post this issue here)

Edit : I have v2.0.1 of ytdl-core

**Comment by fent** [comment]
make sure you're on latest with `npm ls ytdl-core`

**Comment by Spokloo** [comment]
I did npm i ytdl-core@latest a earlier and it downloaded the 2.0.1

**Comment by Spokloo** [comment]
Can someone help me please, I still have this issue

**Comment by fent** [comment]
the latest version does not contain that warning, so there's something else going on.

look in your `package.json` and `package-lock.json` for ytdl-core and see what version it is.

**Comment by Spokloo** [comment]
I checked and it's written ^2.0.1

**Comment by Spokloo** [comment]
![ytdl1](https://user-images.githubusercontent.com/43513707/79009184-3afd2680-7b5f-11ea-874c-4b34780e570a.PNG)
![ytdl2](https://user-images.githubusercontent.com/43513707/79009177-39cbf980-7b5f-11ea-8fe9-f23901069003.PNG)
![ytdl3](https://user-images.githubusercontent.com/43513707/79009181-3afd2680-7b5f-11ea-8d36-3a07aedf2d6f.PNG)

**Comment by IgorZimmermann** [comment]
i have the same issue

**Comment by Melonai** [comment]
If you are using ytdl-core-discord like the discordjs guide recommends doing, that package uses an older version of ytdl-core which throws this error.

**Comment by Spokloo** [comment]
I indeed use ytdl-core-discord, which version should i take of ytdl-core then ?

**Comment by Melonai** [comment]
ytdl-core-discord currently does not have a later version available to fix this. A temporary fix I've found is just taking the ytdl-core-discord index.js file, saving it locally into your project and instead of requiring ytdl-core-discord just requiring that file instead. Your project would also need to have the latest of version of prism-media as a dependency if you go that route. 
To make it work properly one last thing you will need to do is modifying the filter function in your new file to not check for the audio sample rate, as the newer version of ytdl-core sometimes doesn't return it. This fixed it for me.
Once ytdl-core-discord is updated you can remove this new file and add the newest version of ytdl-core-discord back as a dependency.

**Comment by rqbik** [comment]
Actually, you can try and install package with updated version of `ytdl-core` yourself.

If you are using npm, see [this](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) stackoverflow thread on how to install package with updated dependency. 

If you are using yarn, see [this](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) yarn docs page on Selective dependency resolutions.

**Comment by Pabszito** [comment]
I fixed this problem + another one (This video is unavailable) uninstalling ytdl-core-discord and updating prism-media.
