### ISSUE TITLE
Output googlevideo URL instead of file?

### ISSUE THREAD

**Issue by PrinceKomali** [fent/node-ytdl-core#673]
I'm trying to use this with Discord.js and the file limit keeps coming into play, is there a way to just output the URL to download?

**Comment by Aasim-A** [comment]
If you want the default format that `ytdl` chooses; this is the way to get it:
```javascript
  // You can use .then syntax as well
  const info = await ytdl.getInfo(url);
  const format = ytdl.chooseFormat(info.formats, { quality: 'highest' });
  // then the google video url is under format.url
```
otherwise you'll have to specify which format you want, look in the formats section in the [docs](https://github.com/fent/node-ytdl-core#ytdlurl-options).
Keep in mind that this link is temporary it is only valid for 6 hours.

**Comment by PrinceKomali** [comment]
The 6 hour thing actually is perfect! Thank you!

**Comment by Aasim-A** [comment]
👍
