### ISSUE TITLE
How to download only audio MP3 format

### ISSUE THREAD

**Issue by dimeks** [fent/node-ytdl-core#712]
ytdl(URL, {
    format: 'mp3'
    }).pipe(res);
ytdl.getBasicInfo(URL, (err, info) => {
        const {title} = info;
        if (err) return console.error(err);
        res.header('Content-Disposition', `attachment; filename=${title}.mp3`);
});
});

**Comment by Roki100** [comment]
Youtube does not provide mp3 format, you have to use FFmpeg for that
See [example/convert_to_mp3.js](https://github.com/fent/node-ytdl-core/blob/master/example/convert_to_mp3.js)

**Comment by dimeks** [comment]
throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg

**Comment by fent** [comment]
use `filter: 'audioonly'`. see the readme for more options.

**Comment by mrsajadpp** [comment]
i cant hear audio
```
res.header('Content-Disposition', 'attachment; filename="' + new Date() + '-Fizzy.mp3"');
ytdl(req.body.url, { format: 'mp3', filter: 'audioonly' }).pipe(res);
```

**Comment by LuanRT** [comment]
@mrsajadpp 
As someone already pointed out above, YouTube does not provide `mp3` audio formats. Your file can't be played because you're using the wrong extension, try saving it as `.m4a` instead and remove the `format: 'mp3'` from the options.

If you really want `mp3` (note that `m4a` has better quality), then you'll have to re-encode it using ffmpeg.

**Comment by mrsajadpp** [comment]
> 

It's not working...

**Comment by eliasmurcray** [comment]
Renaming to .webm worked for me.

**Comment by mrsajadpp** [comment]
not working for me
