### ISSUE TITLE
Stream doesn't end when video is done downloading

### ISSUE THREAD

**Issue by ryanburnette** [fent/node-ytdl-core#819]
Environment info

```bash
$ node -v
v14.15.1

$ cat package.json | grep ytdl-core
    "ytdl-core": "^4.1.4"
```

Code I'm running: (the demo from readme)

```js
const fs = require('fs');
const ytdl = require('ytdl-core');
ytdl('http://www.youtube.com/watch?v=aqz-KE-bpKQ')
  .pipe(fs.createWriteStream('video.mp4'));
```

The issue is that the stream doesn't end at the end of the video, so the process doesn't exit.

**Comment by ryanburnette** [comment]
This works though...

```js
const fs = require("fs");
const ytdl = require("ytdl-core");
ytdl("http://www.youtube.com/watch?v=aqz-KE-bpKQ")
  .pipe(fs.createWriteStream("video.mp4"))
  .end(function () {
    process.exit();
  });
```

**Comment by ryanburnette** [comment]
This is what I needed. Just needed a way to know when the download is done.

```js
ytdl("http://www.youtube.com/watch?v=aqz-KE-bpKQ")
  .pipe(fs.createWriteStream("video.mp4"))
  .on("close", function () {
    process.exit();
  });
```

**Comment by coolaj86** [comment]
That will sometimes result in the application being closed before the last packet of data is written to disk. Use this instead:

```js
let ws = fs.createWriteStream("video.mp4");
ytdl("http://www.youtube.com/watch?v=aqz-KE-bpKQ")
  .pipe(ws)
  .on("close", function () {
    ws.close();
  });
ws.on('close', function () {
    process.exit();
});
```

Pipes don't close automatically because... some reason I can't remember, but it's a valid reason. Pipes are used for more than just files - http streams, etc.

As to why the program just hangs there instead of exiting... probably missing a weak reference (`unref()`) somewhere on a timer or network connection:

- https://nodejs.org/api/net.html#net_server_unref
- https://nodejs.org/api/timers.html#timers_timeout_unref

**Comment by ryanburnette** [comment]
> As to why the program just hangs there instead of exiting... probably missing a weak reference (unref()) somewhere on a timer or network connection:

Based on this, I'm going to reopen the issue so one of the maintainers can take a look.

**Comment by fent** [comment]
the program hangs because the request cache uses timeouts

**Comment by coolaj86** [comment]
> request cache

Where is that? Could we add some `.unref()`s to those timeouts to keep them weak?

**Comment by Brainicism** [comment]
> the program hangs because the request cache uses timeouts

Is this the intended behavior? Requiring a `process.exit()` to cleanly exit the program because of a cache timer seems not so intuitive
