### ISSUE TITLE
Provide an API to disable update checking

### ISSUE THREAD

**Issue by flaviotordini** [fent/node-ytdl-core#842]
Setting an env variable is not always possibile. It would be great to have some Javascript way to disable update checking.

**Comment by Peppy8651** [comment]
Why do you need a .env variable to turn off a warning, and ytdl-core should not require a whole API just to turn off a simple warning.

**Comment by flaviotordini** [comment]
The problem is not the warning. The github http request is sometimes undesiderable. 

Btw I found that I could do:

`ytdl.lastUpdateCheck = Date.now();
`

So the API is already there but undocumented.

**Comment by redbrain** [comment]
You can also set `ytdl.lastUpdateCheck` to a very high number. For example, `2147483647` would delay checks until 2038.
Since the API is there (although undocumented), I guess you could close this issue for now.
I'd normally advise against disabling update warnings, but I suppose preventing GitHub requests is a valid reason.
