### ISSUE TITLE
Livetreams only work for a few seconds with audioonly filter

### ISSUE THREAD

**Issue by fbagjug** [fent/node-ytdl-core#886]
When playing a live stream it only works for 2-3 seconds before stopping when using the `audioonly` filter.
Here is the code I am using:
```
let songInfo = ytdl.getInfo(link_of_lofi);
let connection = await msg.member.voice.channel.join();
let dispatcher = connection.play(ytdl.downloadFromInfo(songInfo, { highWaterMark: 1<<12, filter: 'audioonly' }));
```
Livestream example: https://www.youtube.com/watch?v=5qap5aO4i9A

**Comment by fbagjug** [comment]
Another issue I found was when trying to play: https://www.youtube.com/watch?v=TGqBs9Fx1bM (alan walker faded low quality), it doesn't even attempt to play anything. I added an unpipe listener to the dispatcher and it instantly triggers, I couldn't figure out what caused it whether it was YTDL or the dispatcher. I added the audioonly filter and it appeared to fix this issue.

**Comment by Svallinn** [comment]
For live streams, filtering audio only is not enough.
You need to make sure that, whatever format you pick, it utilizes the HLS protocol.
You can do that (combined with filtering for only audio) by doing this:
```js
ytdl.downloadFromInfo(songInfo, { highWaterMark: 1<<12, filter: format => !format.hasVideo && format.isHLS })
```
*Although, either a notice for this should be up somewhere on the docs in BIG LETTERS or, better yet (fyi this is just my own opinion), the library itself should filter out non-HLS streams when it comes to live streams, just like the* `youtube-dl` *cmdline utility does*

**Comment by fbagjug** [comment]
That seemed to give me the error `Error: No such format found: highest`

**Comment by fbagjug** [comment]
I'm not sure why but using the filter `audio` seems to work better than `audioonly`

**Comment by Svallinn** [comment]
For live streams, you can't just filter audio like that.
You need to make sure that, whatever format you pick, it utilizes the **HLS** protocol.
And, unfortunately, this means that video comes along with it, which means bigger bandwidth use, whether you like it or not.

Discord.js can **most likely** (and I say that because I don't use it) deal with it by using FFmpeg to separate the audio from the video and play the audio
___
Anyway, most of the time (or all of the time, I have no patience to test), the formats with quality labels of 720p and above have the best `audioBitrate` possible
Therefore, I suggest the following logic ***(for live streams)***
```js
let songInfo = ytdl.getInfo(link_of_lofi);
let options = { highWaterMark: 1<<12 };

if (songInfo.videoDetails.isLive) {
  // Then this is a live stream
  let hlsFormats = ytdl.filterFormats(songInfo.formats, (format) => format.isHLS);
  let topFormatLabel = hlsFormats[0].qualityLabel;

  // Remove the p from qualityLabel and cast to number
  let rawQuality = parseInt(topFormatLabel.slice(0, topFormatLabel.length - 1));
  // If the video quality is higher than 720p, then we wanna make sure
  // to get the highest audio quality from the lowest possible video quality
  // (e.g. 1080p and 720p provide the same audio bitrate,
  //  so obviously the 720p is more desirable to save bandwidth)
  if (rawQuality > 720) {
    options.filter = (format) => format.isHLS && format.qualityLabel === '720p';
  } else {
    options.filter = (format) => format.isHLS;
  }
} else {
  // code for non-live streams
}

let connection = await msg.member.voice.channel.join();
let dispatcher = connection.play(ytdl.downloadFromInfo(songInfo, options));
```
(you can also use *itag* values instead of filtering like this if you know what those itags are)

*It's also worth noting that a notice for this use case should be up somewhere on the docs in BIG LETTERS or, better yet (fyi this is just my own opinion), the library itself should filter out non-HLS streams when it comes to live streams, just like the* `youtube-dl` *cmdline utility does*

**Comment by AimSai59** [comment]
After trying recently, the problem is not solved on my side. 
For streams, I use this and it works perfectly:

`  
    const videoUrl = <Your URL here>;
    const songInfo = await ytdl.getInfo(videoUrl);
    const stream = () => {
        // live stream
        if (songInfo.videoDetails.isLive) {
            const format = ytdl.chooseFormat(songInfo.formats, { quality: [128,127,120,96,95,94,93] });
            return format.url;
        } else {
            return ytdl.downloadFromInfo(songInfo, { filter: 'audioonly' });
        }
    }

    let connection = await voiceChannel.join();
    // play
   connection.play(stream());

Hopefully this will be useful to you
