### ISSUE TITLE
time query support?

### ISSUE THREAD

**Issue by Oky12** [fent/node-ytdl-core#909]
since begin option is not working for non live video. so I tried to find an alternative to play a youtube video at a certain time on my discord bot. and i found on stackoverflow using seek option on discord ffmpeg. 
```js
var option = { filter: "audioonly", highWaterMark: 1048576 };
const streamYtdl = ytdl(streamUrl, option);
let dispatcher = connection.play( streamYtdl, { seek: begin })
```
But sometimes that method gives some error from user like invalid time and many more. well... i can fix it. 😑
but i think this not a good alternative of ytdl begin option. because when i try play on specific time like 2m00s. my bot must waiting ytdl downloading stream data until is got that time. 😟
so i try to learn how youtube play some video on specific time and i found something like this `t=60`.

youtube uses some sort of query time in the video url. so I tried to add it to a youtube video link like this
`https://www.youtube.com/watch?v=ZNFKZI7L9xE&t=50` then play to my discord bot. and its not working.

Does ytdl support time queries? or should I use the `begin` option? or back using `seek` option?

_sorry for my bad english_

**Comment by TimeForANinja** [comment]
> Does ytdl support time queries?

Sorry, but no. We extract the videoID from the link - that's about it.
Youtube itself does not change the content when you provide the `t=xxx` query - the player on the webpage parses the query somehow manages to skip part of the video.

> or should I use the begin option?

that one is deprecated since YouTube somestimes supports it and sometimes they don't....

> or back using seek option?

what you can try to do is let ffmpeg do the seeking. ATM you pass a stream to FFmpeg. FFmpeg has no idea how to seek in that other than reading until it is where it wants to be. If you directly pass the formet-url to FFmpeg it might be able to directly skip to the position you wanna seek to. I haven't tried this thou and would enjoy hearing back from you if this worked.
